# 原来的: base_url = "https://yihong0618.github.io/gitblog/"
# 修改为你的自定义域名，注意要把后面的 /gitblog/ 去掉，因为你是自定义域名，通常是在根目录下
base_url = "https://murmur.cnaron.com"

generate_feeds = true
feed_filenames = ["rss.xml"]
theme = "even"
taxonomies = [
    {name = "categories", feed = true},
    {name = "tags", feed = true},
]
[extra]
even_title = "naron's Blog"  # 这里建议改成你自己的名字
even_menu = [
    {url = "$BASE_URL", name = "Home"},
    {url = "$BASE_URL/tags/top/", name = "Top"},
    {url = "$BASE_URL/issue-282/", name = "About"}, # 确保你有 issue 282，或者是你自己 About 的 issue id
    {url = "$BASE_URL/issue-311/", name = "Things I like"}, # 同上，确保 issue id 对应你的
]
